name: workout_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # cupertino icons
  cupertino_icons: ^0.1.2
  # provider
  provider: ^4.0.4
  #get it
  get_it: ^4.0.1
  # shared preferences
  shared_preferences: ^0.5.6+3
  # giffy dialog
  giffy_dialog: ^1.7.0
  # provider architecture
  provider_architecture: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/